-   name: Start Deluge
    block:
        -   name: Create Deluge directories
            ansible.builtin.file:
                path: "{{ item }}"
                state: directory
            with_items:
                - "{{ deluge.config.directory }}"

        -   name: Copy Deluge docker-compose template
            ansible.builtin.template:
                src: templates/docker-compose.yml.j2
                dest: "{{ deluge.config.directory }}/docker-compose.yml"
            notify: Restart Deluge

        -   name: Ensure Deluge is running
            community.docker.docker_compose_v2:
                project_src: "{{ deluge.config.directory }}/"
                build: never
    when: deluge.enabled

-   name: Stop Deluge
    block:
        -   name: Stop Deluge
            community.docker.docker_compose_v2:
                project_src: "{{ deluge.config.directory }}/"
                build: never
                state: absent
    when: not deluge.enabled
