collections:
    - community.docker
    - community.general

roles:
    - name: geerlingguy.security
    - name: geerlingguy.firewall
    - name: geerlingguy.git
    - name: geerlingguy.pip
    - name: geerlingguy.docker
