jellyfin:
    enabled: false

    docker:
        container:
            name: "jellyfin"
        image:
            name: "jellyfin/jellyfin"
            version: "latest"

    proxy:
        hostname: "jellyfin"
        port: 8096
        local_only: true

    config:
        directory: "{{ root.config.directory }}/jellyfin"
