deluge:
    enabled: false

    docker:
        container:
            name: "deluge"
        image:
            name: "lscr.io/linuxserver/deluge"
            version: "latest"

    proxy:
        hostname: "deluge"
        port: 8112
        local_only: true

    config:
        directory: "{{ root.config.directory }}/deluge"

        extra_mounts:
            -   src: ~
                dest: ~
