homepage:
    enabled: false

    docker:
        container:
            name: "homepage"
        image:
            name: "ghcr.io/gethomepage/homepage"
            version: "latest"

    proxy:
        hostname: "homepage"
        port: 3000
        local_only: true  # is a bad idea to set to false

    config:
        directory: "{{ root.config.directory }}/homepage"

        settings: # Settings config as https://gethomepage.dev/configs/settings/#title
            title: "Homeserver"
            language: "{{ root.locale }}"
            showStats: true

        services:
            -   Networking:
                    -   Router:
                            icon: Local Router
                            href: http://192.168.0.1/
                            description: Router Homepage

        widgets:
            -   search:
                    provider: google # google, duckduckgo, bing, baidu, brave or custom
                    focus: true # Optional, will set focus to the search bar on page load
                    target: _blank # One of _self, _blank, _parent or _top
            -   resources:
                    cpu: true
                    memory: true
                    cputemp: true
                    uptime: true
                    units: metric # only used by cpu temp
                    refresh: 60000 # optional, in ms

        bookmarks:
            ~
