-   name: Create Deluge folder
    ansible.builtin.file:
        path: "{{ deluge.work_dir }}"
        state: directory
        mode: 0755
    become: false

-   name: Copy Deluge docker-compose template
    ansible.builtin.template:
        src: templates/deluge/docker-compose.yml.j2
        dest: "{{ deluge.work_dir }}/docker-compose.yml"
        mode: 0640
    become: false
    notify: Restart Deluge

-   name: Ensure Deluge is running
    community.docker.docker_compose_v2:
        project_src: "{{ deluge.work_dir }}/"
        build: never
    become: false
